export enum ReportReason {
  SPAM = 'SPAM',
  HARASSMENT_OR_BULLYING = 'HARASSMENT_OR_BULLYING',
  HATE_SPEECH = 'HATE_SPEECH',
  VIOLENCE_OR_THREATS = 'VIOLENCE_OR_THREATS',
  INAPPROPRIATE_CONTENT = 'INAPPROPRIATE_CONTENT',
  FALSE_INFORMATION = 'FALSE_INFORMATION',
  COPYRIGHT_INFRINGEMENT = 'COPYRIGHT_INFRINGEMENT',
  PRIVACY_VIOLATION = 'PRIVACY_VIOLATION',
  SELF_HARM_OR_SUICIDE = 'SELF_HARM_OR_SUICIDE',
  TERRORISM_OR_EXTREMISM = 'TERRORISM_OR_EXTREMISM',
}
